#!/bin/bash

# =======================================================
#  VPS AUTO MAILER (Auto-Detect Domain/Hostname)
# =======================================================

# --- 1. AUTO DETECT SYSTEM (BAGIAN INI OTOMATIS) ---
# Mengambil nama lengkap host (FQDN)
MY_HOSTNAME=$(hostname -f)

# Cek apakah hostname valid (harus punya domain, misal: srv.domain.com)
if [[ "$MY_HOSTNAME" == *"localhost"* ]] || [[ "$MY_HOSTNAME" != *"."* ]]; then
    echo "⚠️  PERINGATAN: Hostname Anda terdeteksi sebagai '$MY_HOSTNAME'."
    echo "    Email kemungkinan besar masuk SPAM atau ditolak."
    echo "    Saran: Ganti hostname jadi domain (contoh: srv1.domainanda.com)"
    echo "    Cara: sudo hostnamectl set-hostname srv1.domainanda.com"
    echo "---------------------------------------------------------------"
    # Fallback default jika hostname error
    MY_HOSTNAME="localhost.localdomain" 
fi

# Set Variabel Otomatis
SENDER_NAME="Admin $MY_HOSTNAME"
SENDER_EMAIL="admin@$MY_HOSTNAME"
REPLY_TO="support@$MY_HOSTNAME"

# --- 2. INPUT USER ---
TARGET_EMAIL="${1:-target@example.com}"
SUBJECT="${2:-Test Auto-Detect dari $MY_HOSTNAME}"

echo ">> Mengirim dari: $SENDER_EMAIL"
echo ">> Mengirim ke  : $TARGET_EMAIL"

# --- 3. GENERATE HEADERS ---
BOUNDARY="AutoBound_$(date +%s)_$(openssl rand -hex 4)"
DATE_NOW=$(date -R)
MSG_ID="<$(date +%s).$(openssl rand -hex 4)@$MY_HOSTNAME>"

# --- 4. ISI PESAN ---
BODY_HTML="
<html>
<body>
  <h2>Halo!</h2>
  <p>Email ini dikirim otomatis dari server: <b>$MY_HOSTNAME</b></p>
  <p>Sistem mendeteksi konfigurasi berikut:</p>
  <ul>
    <li>Sender: $SENDER_EMAIL</li>
    <li>Reply-To: $REPLY_TO</li>
    <li>Date: $DATE_NOW</li>
  </ul>
  <hr>
  <small>Auto-generated by Bash Script</small>
</body>
</html>
"
BODY_TEXT=$(echo "$BODY_HTML" | sed 's/<[^>]*>//g')

# --- 5. EKSEKUSI (SENDMAIL) ---
(
cat <<EOF
From: "$SENDER_NAME" <$SENDER_EMAIL>
To: $TARGET_EMAIL
Reply-To: $REPLY_TO
Subject: $SUBJECT
Date: $DATE_NOW
Message-ID: $MSG_ID
X-Mailer: VPS-Auto-Detect-v2
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="$BOUNDARY"

--$BOUNDARY
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

$BODY_TEXT

--$BOUNDARY
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

$BODY_HTML

--$BOUNDARY--
EOF
) | /usr/sbin/sendmail -t

# --- 6. HASIL ---
if [ $? -eq 0 ]; then
    echo "[SUKSES] Email telah diserahkan ke sistem pengiriman."
else
    echo "[GAGAL] Ada masalah dengan sendmail."
fi
